emcc ./pathfinder/main.c \
      -Os -g1 \
      -s WASM=1 \
      -s MALLOC=emmalloc \
      -s ALLOW_MEMORY_GROWTH=1 \
      -s EXPORT_ES6=1 \
      -s MODULARIZE=1 \
      -s 'EXPORT_NAME="pathfinder"' \
      -s 'ENVIRONMENT="web"' \
      --bind \
      -o pf.mjs || exit 1